name: Deploy to Namecheap via FTP

on:
  push:
    branches:
      - main # o la rama que uses para producci√≥n

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build Astro project
        run: bun run build

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.turismoperu.com.pe
          username: ${{ secrets.FTP_USERNAME_TPC }}
          password: ${{ secrets.FTP_PASSWORD_TPC }}
          local-dir: dist/
          server-dir: /
          security: loose
